import type { RoadStyleElement, RoadStyleProject } from "./types";
import { validateProject } from "./validation";

function formatMlnNumber(value: number): string {
  return value.toFixed(14);
}

function sanitizeMlnToken(value: string): string {
  const safeToken = value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9_-]+/g, "_")
    .replace(/^_+|_+$/g, "");

  return safeToken || "BYLAYER";
}

function compareStringsByCodePoint(a: string, b: string): number {
  if (a === b) {
    return 0;
  }

  return a < b ? -1 : 1;
}

function isWindowsReservedDeviceName(value: string): boolean {
  return /^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/i.test(value);
}

function sortElementsForMln(elements: RoadStyleElement[]): RoadStyleElement[] {
  return [...elements].sort((a, b) => {
    if (b.offset !== a.offset) {
      return b.offset - a.offset;
    }

    return compareStringsByCodePoint(a.name, b.name);
  });
}

export function generateMln(project: RoadStyleProject): string {
  const validation = validateProject(project);
  if (validation.errors.length > 0) {
    throw new Error(`Cannot export MLN: ${validation.errors[0].message}`);
  }

  const enabledElements = sortElementsForMln(project.elements.filter((element) => element.enabled));
  const lines = [
    "MLSTYLE",
    "2",
    ` ${project.styleName.trim()}`,
    "70",
    " 0",
    "3",
    " Generated by Road MLN Generator",
    "62",
    " 0",
    "51",
    " 90.00000000000000",
    "52",
    " 90.00000000000000",
    "71",
    ` ${enabledElements.length}`,
  ];

  for (const element of enabledElements) {
    lines.push(
      "49",
      ` ${formatMlnNumber(element.offset)}`,
      "62",
      ` ${element.color}`,
      "6",
      ` ${sanitizeMlnToken(element.linetype)}`
    );
  }

  lines.push("0");

  return `${lines.join("\n")}\n`;
}

export function getMlnFilename(styleName: string): string {
  const safeName = styleName
    .trim()
    .replace(/[^a-zA-Z0-9_-]+/g, "_")
    .replace(/^_+|_+$/g, "");
  const safeBaseName = safeName || "road-style";

  return `${isWindowsReservedDeviceName(safeBaseName) ? `${safeBaseName}_style` : safeBaseName}.mln`;
}
