import { describe, expect, it } from "vitest";
import { generateMln, getMlnFilename } from "@/lib/road-style/mln";
import { createSimpleUrbanRoadProject } from "@/lib/road-style/templates";

describe("MLN writer", () => {
  it("exports deterministic AutoCAD multiline style content", () => {
    const project = createSimpleUrbanRoadProject();
    project.styleName = "ROAD_TEST";

    expect(generateMln(project)).toBe(`MLSTYLE
2
 ROAD_TEST
70
 0
3
 Generated by Road MLN Generator
62
 0
51
 90.00000000000000
52
 90.00000000000000
71
 5
49
 5.50000000000000
62
 8
6
 CONTINUOUS
49
 3.50000000000000
62
 7
6
 CONTINUOUS
49
 0.00000000000000
62
 1
6
 CENTER
49
 -3.50000000000000
62
 7
6
 CONTINUOUS
49
 -5.50000000000000
62
 8
6
 CONTINUOUS
0
`);
  });

  it("excludes disabled elements", () => {
    const project = createSimpleUrbanRoadProject();
    project.elements[0].enabled = false;

    const mln = generateMln(project);
    const linetypeTokens = mln
      .split("\n")
      .filter((line, index, lines) => lines[index - 1] === "6")
      .map((line) => line.trim());

    expect(mln).toContain("71\n 4");
    expect(linetypeTokens).not.toContain("CENTER");
  });

  it("sanitizes linetype tokens before writing MLN records", () => {
    const project = createSimpleUrbanRoadProject();
    project.elements = [
      {
        id: "unsafe-linetype",
        enabled: true,
        name: "Unsafe Linetype",
        offset: 0,
        color: 2,
        linetype: "dash\n49\n 999",
        role: "custom",
      },
    ];

    expect(generateMln(project)).toBe(`MLSTYLE
2
 ROAD_SIMPLE_URBAN
70
 0
3
 Generated by Road MLN Generator
62
 0
51
 90.00000000000000
52
 90.00000000000000
71
 1
49
 0.00000000000000
62
 2
6
 DASH_49_999
0
`);
  });

  it("sorts equal-offset elements by deterministic string comparison", () => {
    const project = createSimpleUrbanRoadProject();
    project.elements = [
      {
        id: "lower-a",
        enabled: true,
        name: "a",
        offset: 1,
        color: 2,
        linetype: "CONTINUOUS",
        role: "custom",
      },
      {
        id: "upper-b",
        enabled: true,
        name: "B",
        offset: 1,
        color: 3,
        linetype: "CENTER",
        role: "custom",
      },
    ];

    const mln = generateMln(project);

    expect(mln.indexOf(" 3\n6\n CENTER")).toBeLessThan(
      mln.indexOf(" 2\n6\n CONTINUOUS")
    );
  });

  it("throws when export-critical validation fails", () => {
    const project = createSimpleUrbanRoadProject();
    project.styleName = "bad style";

    expect(() => generateMln(project)).toThrow(
      "Cannot export MLN: Style name can use only letters, numbers, underscores, and hyphens."
    );
  });

  it("creates a safe MLN filename", () => {
    expect(getMlnFilename("Road Test")).toBe("Road_Test.mln");
    expect(getMlnFilename("***")).toBe("road-style.mln");
    expect(getMlnFilename("CON")).toBe("CON_style.mln");
    expect(getMlnFilename("com1")).toBe("com1_style.mln");
  });
});
